fix(puppeteer): UnhandledPromiseRejectionWarning: TypeError: console[msg._type] is not a function * page crashing/error emit is logged as a warning to the console * basic puppeteer -> node type mapping is added